OkMuay/Controllers/OkMuayController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OkMuay.Vkontakte;
using System.Web.Configuration;

namespace OkMuay.Controllers
{
    public class OkMuayController : Controller
    {
        public ActionResult Index()
        {
			var api = new VkApi();
			var wall = api.GetWall(WebConfigurationManager.AppSettings["UserId"]);
            return View(wall);
        }

	    public ActionResult Trainings()
	    {
		    return View();
	    }
        

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

	    public ActionResult GetBgPics()
	    {
		    var list = new List<string>();
			var files = new DirectoryInfo(Server.MapPath("~/BgPics/"));
			foreach (var file in files.GetFiles("*.jpg"))
		    {
				list.Add(file.Name);   
		    }

		    return Json(list, JsonRequestBehavior.AllowGet);
	    }
    }
}

OkMuay/Views/OkMuay/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OkMuay/Views/OkMuay/Contact.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Школа Олега Кудринского</title>
	<link rel='shortcut icon' href='/Letour.ico' />
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
	<link href="~/Content/StyleSheet.min.css" rel="stylesheet" />
</head>
<body>
	<div id="background" class="om-background">
		<div id="bg1" class="om-background" style="background-color: black;"></div>
		<div id="bg2" class="om-background" style="background-color: black;"></div>
	</div>

	<div class="om-info-background">
		<div class=" om-zero-index">
			<div class="om-cleaner">
				<h1 class="om-headlines om-left">Контакты</h1>
				<div class="om-right om-wall-post-header">
					<a href="/OkMuay/Trainings">Тренировки</a>&nbsp;
					<a href="/">Главная</a>
				</div>
			</div>

			<div class="om-info-content om-cleaner om-vertical-padding">
				<p class="om-wall-post-header">
					Адрес: город Омск, улица Гагарина, дом 3, вход со стороны улицы Бударина у подземной парковки.<br/>
					Наши телефоны:&nbsp;&nbsp;&nbsp;
					<span class="om-nowrap">(3812) 59-24-26</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<span class="om-nowrap">(3812) 59-24-27</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<span class="om-nowrap">8-904-326-37-27</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					omfk@yandex.ru
				</p>	
			</div>

			<div>
				<script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=4v-xZc5RLuErYm8ZobRnuZhea36rhqBV&width=100%&height=450"></script>
			</div>
			 
			<div class="om-full-width" style="height: 477px;background-image:url('/Images/address.png');background-position: center;background-repeat: no-repeat;background-size: cover;">
			</div>

		</div>
	</div>

	<div class="om-cover">
		<div class="om-cover-outer"></div>
		<div class="om-cover-inner"></div>
	</div>

	<script src="~/Scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Scripts/respond.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>

	<script src="~/Scripts/okMuay/mainPage.js"></script>
</body>
</html>

OkMuay/Views/OkMuay/Index.cshtml
@using OkMuay.Vkontakte
@model OkMuay.Vkontakte.Wall
@{
	Layout = null;
	var wall = Model ?? new Wall();
}	

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Школа Олега Кудринского</title>					   
	<link rel='shortcut icon' href='/Letour.ico' />
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
	<link href="~/Content/StyleSheet.min.css" rel="stylesheet" />
</head>
<body>
	<div id="background" class="om-background">
		<div id="bg1" class="om-background" style="background-color: black;"></div>
		<div id="bg2" class="om-background" style="background-color: black;"></div>
	</div>

	<div class="row om-whole-area om-no-margin om-no-padding om-zero-index">
		<nav class="navbar navbar-default navbar-fixed-top visible-xs" role="navigation">
			<ul class="container nav nav-pills">
				<li><a class="om-big-text om-no-color" href="#">Тренировки</a></li>
				<li><a class="om-big-text om-no-color" href="#">Контакты</a></li>
			</ul>
		</nav>
		<div class="visible-xs" style="margin-top:50px;"></div>
		<div class="col-sm-offset-6 col-sm-6 col-md-offset-7 col-md-5 col-lg-offset-8 col-lg-4 om-full-height om-first-index om-no-padding om-relative">
			<div class="om-minus-index om-wall-container"></div>
			<div id="vkWall" class="om-wall om-first-index">
				@Html.Raw(wall.Render())
				@*AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD*@
			</div>
		</div>
		<div class="om-fixed-regalies hidden-xs" data-toggle="tooltip" data-placement="right" title="Чтобы стать чемпионом нужно ходить на тренировки!">

			<h1>Среди учеников :</h1>
			<ul>
				<li>Чемпионы Мира</li>
				<li>Чемпионы Европы</li>
				<li>Чемпионы России</li>
			</ul>
		</div>
		<div class="om-fixed-menu hidden-xs">
			<div class="row om-no-margin om-no-padding">
				<div class="col-sm-offset-1 col-sm-4 col-md-5 col-lg-6 om-no-padding">
					<ul class="nav nav-pills">
						<li style="float: left;"><a class="om-menu-item" href="/OkMuay/trainings">Тренировки</a></li>
						<li style="float:right;"><a class="om-menu-item" href="/OkMuay/contact">Контакты</a></li>
					</ul>
				</div>
				<div class="col-sm-offset-1 col-sm-6  col-md-5 col-lg-4 om-no-padding"></div>
			</div>
		</div>
		@*<nav class="navbar navbar-default navbar-fixed-bottom visible-xs" role="navigation">
				<ul class="container nav nav-pills">
					<li><a class="om-big-text om-no-color" href="#">Тренировки</a></li>
					<li><a class="om-big-text om-no-color" href="#">Контакты</a></li>
				</ul>
			</nav>*@
		<div class="visible-xs" style="margin-bottom:50px;"></div>
	</div>	 
	
	<div class="om-cover">
		<div class="om-cover-outer"></div>
		<div class="om-cover-inner"></div>
	</div>

	<script src="~/Scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Scripts/respond.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>

	<script src="~/Scripts/okMuay/mainPage.js"></script>
</body>
</html>

OkMuay/Views/OkMuay/Trainings.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Школа Олега Кудринского</title>
	<link rel='shortcut icon' href='/Letour.ico' />
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
	<link href="~/Content/StyleSheet.min.css" rel="stylesheet" />
</head>
<body>
	<div id="background" class="om-background">
		<div id="bg1" class="om-background" style="background-color: black;"></div>
		<div id="bg2" class="om-background" style="background-color: black;"></div>
	</div>

	<div class="om-info-background">
		<div class=" om-zero-index">
			<h1 class="om-headlines om-left">Тренировки</h1>
			<div class="om-right om-wall-post-header">
				<a href="/OkMuay/Contact">Контакты</a>&nbsp;
				<a href="/">Главная</a>
			</div>
			<div>

				<table class="om-wall-post-content" align="center" border="1" cellpadding="5" cellspacing="0" style="width: 100%;">
					<tbody>
						<tr>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								<strong>Понедельник</strong>
							</td>
							<td style="text-align: center;">
								<strong>Вторник</strong>
							</td>
							<td style="text-align: center;">
								<strong>Среда</strong>
							</td>
							<td style="text-align: center;">
								<strong>Четверг</strong>
							</td>
							<td style="text-align: center;">
								<strong>Пятница</strong>
							</td>
							<td style="text-align: center;">
								<strong>Суббота</strong>
							</td>
						</tr>
						<tr>
							<td style="text-align: center;">
								10.00&nbsp; –&nbsp; 11.30
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								дети, юноши
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								дети, юноши
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								дети, юноши
							</td>
						</tr>
						<tr>
							<td style="text-align: center;">
								10.00&nbsp; –&nbsp; 12.30
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								мини-группа дети 9 - 12 лет
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								мини-группа дети 9 - 12 лет
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								мини-группа дети 9 - 12 лет
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
						</tr>
						<tr>
							<td style="text-align: center;">
								12.00&nbsp; –&nbsp; 13.30
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								группа
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								группа
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								группа
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
						</tr>
						<tr>
							<td style="text-align: center;">
								15.00&nbsp; –&nbsp; 16.30
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								юноши 14 - 17 лет
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								юноши 14 - 17 лет
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								юноши 14 - 17 лет
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
						</tr>
						<tr>
							<td style="text-align: center;">
								16.30&nbsp; –&nbsp; 18.00
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								сборная клуба
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								сборная клуба
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								сборная клуба
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
						</tr>
						<tr>
							<td style="text-align: center;">
								17.00&nbsp; –&nbsp; 18.30
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								дети, подростки
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								дети, подростки
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								дети, подростки
							</td>
						</tr>
						<tr>
							<td style="text-align: center;">
								18.30&nbsp; –&nbsp; 20.00
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								юноши, взрослые
							</td>
							<td style="text-align: center;">
								женская школа
							</td>
							<td style="text-align: center;">
								юноши, взрослые
							</td>
							<td style="text-align: center;">
								женская школа
							</td>
							<td style="text-align: center;">
								юноши, взрослые
							</td>
							<td style="text-align: center;">
								женская школа
							</td>
						</tr>
						<tr>
							<td style="text-align: center;">
								20.15&nbsp; –&nbsp; 22.00
							</td>
							<td style="text-align: center;">
								&nbsp;
							</td>
							<td style="text-align: center;">
								юноши, взрослые
							</td>
							<td style="text-align: center;">
								юноши, взрослые
							</td>
							<td style="text-align: center;">
								юноши, взрослые
							</td>
							<td style="text-align: center;">
								юноши, взрослые
							</td>
							<td style="text-align: center;">
								юноши, взрослые
							</td>
							<td style="text-align: center;">
								юноши, взрослые
							</td>
						</tr>
					</tbody>
				</table>

			</div>

			<p class="om-info-content om-vertical-padding">
				Омский Центр Муай-Тай, считающийся на сегодня одним из лучших от Урала до дальнего Востока, едва ли не первым в России начал заниматься развитием тайского бокса ( Муай Тай ) в нашей стране. Начиная с 1992 года, когда был образован Центр, его бессменный старший тренер Олег Владимирович Кудринский который подготовил уже не одного известного в России и за рубежом профессионального спортсмена. В свою очередь, омские мастера Муай-Тай в спортивных боях снискали уважение своих соперников. Воспитанники Олега Кудринского не только вошли в Российскую элиту тайского бокса но также добились высоких результатов на профессиональном ринге Европы.
			</p>
			<p class="om-info-content om-vertical-padding">
				Летур Центр Муай Тай - современный комфортабельный лагерь тайского бокса, соблюдающий традиции Mуай Тай, специализирующийся на подготовке профессионалов и любителей, к важнейшим турнирам и профессиональным боям.Центр Муай Тай оборудован полномасштабным рингом фирмы EVERLAST, боксерскими мешками, грушами, лапами и другим необходимым оборудованием для отработки ударной техники Mуай Тай, современный гимнастический зал для занятий. Цель нашего лагеря состоит в том, чтобы преподавать и делать доступными для всех желающих, приемы и технику традиционного Муай Тай, поставить ударную технику рук, ног, локтей и ударов коленями, а также работу в клинче, для спортсменов Муай Тай, К-1, кикбоксинга, классического бокса и обучить приемам самозащиты. В нашем лагере тренируются не только профессионалы и любители различного уровня, но и начинающие спортсмены всех возрастов, как мужского, так и женского пола. Летур Центр Муай Тай работает как с отдельными спортсменами, так и сотрудничает с различными Международными и национальными федерациями и клубами.
			</p>
			<p class="om-info-content om-vertical-padding">
				В нашем лагере проходили свою подготовку к ответственным Чемпионатам и турнирам спортсмены из разных стран. В лагере так же осуществляли свою подготовку команды России, Ирана, Казахстана, Германии, Голандии, Харватии и др. Летур Центр Муай Тай также обладает собственной командой профессионалов на постоянной основе, куда, кроме известных Российских профессионалов, входят спортсмены различных стран.
			</p>
			<p class ="om-info-content om-vertical-padding">
				Спортсмены команды Летур Центр Муай Тай участвовали в профессиональных боях на стадионах Таиланда и участвовали в Титульных боях за звание чемпиона Мира и Интерконтинентального Чемпиона, а так же представляли сборную России в матчевых встречах профессионалов Россия - Таиланд, Россия - Голландия, Россия-Иран, Россия - Харватия. Спортсмены лагеря участвовали в любительских Чемпионатах России, Мира и Европы.
			</p>
		<div class="row om-no-margin om-no-padding om-info-content">
		    <div class="img-responsive" style="float:left;padding-right: 10px">
		        <img class="img-responsive img-thumbnail" alt="Старший тренер Олег Кудринский" src="/Images/okudrinsky.jpg" />
		    </div>
		    <div class="">
		        <b>Старший тренер КРУ - Олег Кудринский</b><br />

		        Олег Владимирович Кудринский - Заслуженный наставник, Президент и старший тренер Профессиональной Бойцовской Ассоциации Муай Тай и Омской Федерации Тайского Бокса.  Стаж занятий Муай Тай - 20 лет. Обладатель черного пояса (2 дан) по тае квон до, черного пояса (6 дан) по полноконтактному каратэ. Чемпион Азии, Чемпион Европы по тайскому боксу, неоднократный победитель профессиональных Международных турниров в Тайланде. Аттестации - Тайланд, США, Германии, Аргентина. Прошел профессиональную подготовку в Королевстве Таиланд. Арджарн - Мастер Муай Тай 14 кхан по Муай-Тай. Официальный представитель тренировочного лагеря "Сит Йодтхонг" - доктора Йодтонг Сенанана (Тайланд).
		    </div>
		</div>
		<div class="row om-no-margin om-no-padding om-info-content">
		    <div class="img-responsive om-half-width" style="float:left;padding-right: 10px">
		        <img class="img-responsive img-thumbnail " alt="Тренер женской команды - Татьяна Кудринская" src="/Images/tkudrinskaya.jpg" />
		    </div>
		    <div class="">
		        <b>Тренер женской команды - Татьяна Кудринская</b><br />
		        11-Кхан Муай Тай (прошла стажировку и аттестацию в Тайланде), неоднократная Чемпионка Международных профессиональных турниров в Тайланде, Чемпионка стадиона Тепрасит (Тайланд), воспитала Чемпионку Мира – 2015г., две серебряных призерки Чемпионатов Мира по Муай Тай – 2013,2017г.г., Бронзовую Призерку Чемпионата Мира – 2013г, Чемпионку Европы – 2014г
		    </div>
		</div>
        
		<div class="row om-no-margin om-no-padding om-info-content">
		    <div class="img-responsive om-half-width" style="float:left;padding-right: 10px">
		        <img class="img-responsive img-thumbnail " alt="Тренер взрослой группы  - Владислав Попов" src="/Images/vpopov.jpg" />
		    </div>
		    <div class="">
		        <b>Тренер взрослой группы  - Владислав Попов </b><br />
                10 Кхан Муай Тай, 4-х кратный Чемпион Мира по Муай Тай, 2-х кратный Чемпион Европы 
		    </div>
		</div>
            
		<div class="row om-no-margin om-no-padding om-info-content ">
		    <div class="img-responsive om-half-width" style="float:left;padding-right: 10px">
		        <img class="img-responsive img-thumbnail" alt="Тренер детской команды - Сергей Соболев" src="/Images/ssobolev.jpg" />
		    </div>
		    <div class="">
		        <b>Тренер детской команды - Сергей Соболев</b><br />
                9-Кхан Муай Тай, Бронзовый призер Чемпионата Мира по Муай Тай – 2016 года
		    </div>
		</div>
		
		<div class="om-vertical-padding">
		    
		</div>
                
		<div class="om-center" >
				<iframe class="om-inline-block" width="640" height="360" src="//www.youtube.com/embed/REGaJRq_EpI?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>
				<br />
				<iframe class="om-inline-block" src="http://vk.com/video_ext.php?oid=12343864&id=161507180&hash=300230fd09a086c0&hd=1" width="640" height="360" frameborder="0"></iframe>
			</div>
		</div>
	</div>

	<div class="om-cover">
		<div class="om-cover-outer"></div>
		<div class="om-cover-inner"></div>
	</div>

	<script src="~/Scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Scripts/respond.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>

	<script src="~/Scripts/okMuay/mainPage.js"></script>
</body>
</html>

OkMuay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
	            @Html.ActionLink("Application name", "Index", "OkMuay", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "OkMuay")</li>
                    <li>@Html.ActionLink("About", "About", "OkMuay")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "OkMuay")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>